### ISSUE TITLE
Compressed video not able to stream

### ISSUE THREAD

**Issue by chetanurmaliya** [lalongooo/VideoCompressor#20]
Compressed video not able to stream, Is there any specific settings for streaming video ?

**Comment by lalongooo** [comment]
Not sure @chetanurmaliya, this project is not intended to stream video. It's about compressing videos. I think you should review how you're trying to stream your video.

**Comment by chetanurmaliya** [comment]
Thanks for the response.

Already verified as my player is able to stream the streaming video. 
So that there is some configuration in video compression for streaming video.

In MediaController I made some changes, But still it is not  able to stream.
public String convertVideo(final String path) {
......
utputFormat.setInteger(MediaFormat.KEY_FRAME_RATE, 25);
outputFormat.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 2);
}

Please provide any suggestion if you get.

**Comment by lalongooo** [comment]
Not sure what could fix your issue. As mentioned, the project is based in the source code of the Telegram for Android app. I have no idea about video metadata (an related stuff), I just took the compression part of the Telegram for Android app and made it available for all of you.

One thing you could do is:
1. Try to compress a video using the official Telegram for Android app.
2. Try to stream the compressed video.
3. If it works, then the problem is with this repo, if it doesn't the problem is the Telegram source code and I'm not able to fix that. Note: Please, consider that this repo is based on an old version of the official app. An upgrade is needed for this repo, but not ETA at this time.

**Comment by chetanurmaliya** [comment]
Thanks a lot @lalongooo.
I will check for the same.

**Comment by sourcebits-vaishali** [comment]
Hi 
I am not able to compress the video.I have not changed the code .The size got increased while I compress it.
Can anyone tell me whats the issue?

**Comment by lalongooo** [comment]
@sourcebits-vaishali What android API version are you testing against?

**Comment by sourcebits-vaishali** [comment]
Hi
I am using 23.0 api version. My jni library is not loading. I am getting this error
JNI_OnLoad failed on a previous attempt to load "/data/app/org.example.messenger-2/lib/arm/libtmessages.22.so"
